version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle"}}
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle"}}
      - run:
          name: Run unit tests
          command: ./gradlew testDebugUnitTest
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-24;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-24;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Waiting for emulator
          command: |
              circle-android wait-for-boot
              sleep 30
              adb shell input keyevent 82
              adb shell svc power stayon true
              adb shell settings put global window_animation_scale 0
              adb shell settings put global transition_animation_scale 0
              adb shell settings put global animator_duration_scale 0
      - run:
          name: Run UI tests
          command: ./gradlew :app:connectedDebugAndroidTest -PdisablePreDex
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
path: app/build/test-results
